steps:
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', '-r', $_MODEL_EXPORT, 'saved-model']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_MODEL_SERVICE', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/$_MODEL_SERVICE"]
#- name: gcr.io/cloud-builders/gcloud
#  args: ['run', 'deploy', $_MODEL_SERVICE, '--image', 'gcr.io/$PROJECT_ID/$_MODEL_SERVICE', '--region', 'us-central1', '--allow-unauthenticated']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', $_MODEL_SERVICE, '--image', 'gcr.io/$PROJECT_ID/$_MODEL_SERVICE', '--region', 'us-central1', '--allow-unauthenticated', '--platform', 'managed']
images:
- gcr.io/$PROJECT_ID/$_MODEL_SERVICE
